[build-system]
build-backend = 'setuptools.build_meta'
requires = ['setuptools >= 61.0.0']

[project]
authors = [
  {name = 'The Probabilists', email = 'theprobabilists@gmail.com'}
]
classifiers = [
  'Intended Audience :: Developers',
  'Intended Audience :: Science/Research',
  'Natural Language :: English',
  'Operating System :: OS Independent',
  'Programming Language :: Python :: 3.10',
  'Programming Language :: Python :: 3.9',
  'Programming Language :: Python :: 3.8'
]
description = 'Normalizing flows in PyTorch'
dynamic = ['version', 'dependencies']
keywords = ['torch', 'normalizing flows', 'probability', 'density', 'generative', 'deep learning']
name = 'zuko'
readme = 'README.md'
requires-python = '>=3.8.0'
urls = {documentation = 'https://zuko.readthedocs.io', source = 'https://github.com/probabilists/zuko', tracker = 'https://github.com/probabilists/zuko/issues'}

[project.optional-dependencies]
develop = [
  'pre-commit',
  'pytest',
  'python-lsp-ruff',
  'python-lsp-server[all]',
  'ruff'
]

[tool.ruff]
indent-width = 4
# Same as Black.
line-length = 88
# Assume Python 3.8
target-version = "py38"

[tool.ruff.format]
# Like Black, indent with spaces, rather than tabs.
indent-style = "space"
# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
# Like Black, use double quotes for strings.
quote-style = "double"
# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

[tool.ruff.lint]
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
ignore = ["E501"]
# Enable Pyflakes (`F`) and the pycodestyle (`E`) codes
select = ["E", "F"]
unfixable = []

[tool.setuptools.dynamic]
dependencies = {file = 'requirements.txt'}
version = {attr = 'zuko.__version__'}
